//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommonRos2
{
    [Serializable]
    public class DropperServiceResponse : Message
    {
        public const string k_RosMessageName = "sonia_common_ros2/DropperService";
        public override string RosMessageName => k_RosMessageName;

        public byte result;

        public DropperServiceResponse()
        {
            this.result = 0;
        }

        public DropperServiceResponse(byte result)
        {
            this.result = result;
        }

        public static DropperServiceResponse Deserialize(MessageDeserializer deserializer) => new DropperServiceResponse(deserializer);

        private DropperServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "DropperServiceResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
