//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommonRos2
{
    [Serializable]
    public class DropperServiceRequest : Message
    {
        public const string k_RosMessageName = "sonia_common_ros2/DropperService";
        public override string RosMessageName => k_RosMessageName;

        public const byte PORT_SIDE = 0;
        public const byte STARBOARD = 1;
        public byte side;

        public DropperServiceRequest()
        {
            this.side = 0;
        }

        public DropperServiceRequest(byte side)
        {
            this.side = side;
        }

        public static DropperServiceRequest Deserialize(MessageDeserializer deserializer) => new DropperServiceRequest(deserializer);

        private DropperServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.side);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.side);
        }

        public override string ToString()
        {
            return "DropperServiceRequest: " +
            "\nside: " + side.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
