//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommonRos2
{
    [Serializable]
    public class SerialServiceResponse : Message
    {
        public const string k_RosMessageName = "sonia_common_ros2/SerialService";
        public override string RosMessageName => k_RosMessageName;

        public const byte SUCCESS = 0;
        public const byte FAILED = 1;
        public const byte NO_RESPONSE = 2;
        public const byte CONNECTION_FAILED = 3;
        public byte status;
        public SerialMessageMsg data;

        public SerialServiceResponse()
        {
            this.status = 0;
            this.data = new SerialMessageMsg();
        }

        public SerialServiceResponse(byte status, SerialMessageMsg data)
        {
            this.status = status;
            this.data = data;
        }

        public static SerialServiceResponse Deserialize(MessageDeserializer deserializer) => new SerialServiceResponse(deserializer);

        private SerialServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
            this.data = SerialMessageMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "SerialServiceResponse: " +
            "\nstatus: " + status.ToString() +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
