//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommonRos2
{
    [Serializable]
    public class SerialServiceRequest : Message
    {
        public const string k_RosMessageName = "sonia_common_ros2/SerialService";
        public override string RosMessageName => k_RosMessageName;

        public SerialMessageMsg data;

        public SerialServiceRequest()
        {
            this.data = new SerialMessageMsg();
        }

        public SerialServiceRequest(SerialMessageMsg data)
        {
            this.data = data;
        }

        public static SerialServiceRequest Deserialize(MessageDeserializer deserializer) => new SerialServiceRequest(deserializer);

        private SerialServiceRequest(MessageDeserializer deserializer)
        {
            this.data = SerialMessageMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "SerialServiceRequest: " +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
