//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class ActuatorSendReplyMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/ActuatorSendReply";
        public override string RosMessageName => k_RosMessageName;

        public const byte ELEMENT_TORPEDO = 0;
        public const byte ELEMENT_DROPPER = 1;
        public const byte ELEMENT_ARM = 2;
        public const byte SIDE_PORT = 0;
        public const byte SIDE_STARBOARD = 1;
        public const byte ARM_CLOSE = 0;
        public const byte ARM_OPEN = 1;
        public const byte RESPONSE_FAILURE = 0;
        public const byte RESPONSE_SUCCESS = 1;
        public const byte RESPONSE_TIMED_OUT = 2;
        public byte element;
        public byte side;
        public byte response;

        public ActuatorSendReplyMsg()
        {
            this.element = 0;
            this.side = 0;
            this.response = 0;
        }

        public ActuatorSendReplyMsg(byte element, byte side, byte response)
        {
            this.element = element;
            this.side = side;
            this.response = response;
        }

        public static ActuatorSendReplyMsg Deserialize(MessageDeserializer deserializer) => new ActuatorSendReplyMsg(deserializer);

        private ActuatorSendReplyMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.element);
            deserializer.Read(out this.side);
            deserializer.Read(out this.response);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.element);
            serializer.Write(this.side);
            serializer.Write(this.response);
        }

        public override string ToString()
        {
            return "ActuatorSendReplyMsg: " +
            "\nelement: " + element.ToString() +
            "\nside: " + side.ToString() +
            "\nresponse: " + response.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
