//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class BodyVelocityDVLMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/BodyVelocityDVL";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double xVelBtm;
        public double yVelBtm;
        public double zVelBtm;
        public double eVelBtm;
        public double velocity1;
        public double velocity2;
        public double velocity3;
        public double velocity4;

        public BodyVelocityDVLMsg()
        {
            this.header = new Std.HeaderMsg();
            this.xVelBtm = 0.0;
            this.yVelBtm = 0.0;
            this.zVelBtm = 0.0;
            this.eVelBtm = 0.0;
            this.velocity1 = 0.0;
            this.velocity2 = 0.0;
            this.velocity3 = 0.0;
            this.velocity4 = 0.0;
        }

        public BodyVelocityDVLMsg(Std.HeaderMsg header, double xVelBtm, double yVelBtm, double zVelBtm, double eVelBtm, double velocity1, double velocity2, double velocity3, double velocity4)
        {
            this.header = header;
            this.xVelBtm = xVelBtm;
            this.yVelBtm = yVelBtm;
            this.zVelBtm = zVelBtm;
            this.eVelBtm = eVelBtm;
            this.velocity1 = velocity1;
            this.velocity2 = velocity2;
            this.velocity3 = velocity3;
            this.velocity4 = velocity4;
        }

        public static BodyVelocityDVLMsg Deserialize(MessageDeserializer deserializer) => new BodyVelocityDVLMsg(deserializer);

        private BodyVelocityDVLMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.xVelBtm);
            deserializer.Read(out this.yVelBtm);
            deserializer.Read(out this.zVelBtm);
            deserializer.Read(out this.eVelBtm);
            deserializer.Read(out this.velocity1);
            deserializer.Read(out this.velocity2);
            deserializer.Read(out this.velocity3);
            deserializer.Read(out this.velocity4);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.xVelBtm);
            serializer.Write(this.yVelBtm);
            serializer.Write(this.zVelBtm);
            serializer.Write(this.eVelBtm);
            serializer.Write(this.velocity1);
            serializer.Write(this.velocity2);
            serializer.Write(this.velocity3);
            serializer.Write(this.velocity4);
        }

        public override string ToString()
        {
            return "BodyVelocityDVLMsg: " +
            "\nheader: " + header.ToString() +
            "\nxVelBtm: " + xVelBtm.ToString() +
            "\nyVelBtm: " + yVelBtm.ToString() +
            "\nzVelBtm: " + zVelBtm.ToString() +
            "\neVelBtm: " + eVelBtm.ToString() +
            "\nvelocity1: " + velocity1.ToString() +
            "\nvelocity2: " + velocity2.ToString() +
            "\nvelocity3: " + velocity3.ToString() +
            "\nvelocity4: " + velocity4.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
