//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class DetectionMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/Detection";
        public override string RosMessageName => k_RosMessageName;

        // Name of classe
        public string class_name;
        // Prediction confidence
        public float confidence;
        //  2D bounding box surrounding the object.
        public double top;
        public double left;
        public double bottom;
        public double right;

        public DetectionMsg()
        {
            this.class_name = "";
            this.confidence = 0.0f;
            this.top = 0.0;
            this.left = 0.0;
            this.bottom = 0.0;
            this.right = 0.0;
        }

        public DetectionMsg(string class_name, float confidence, double top, double left, double bottom, double right)
        {
            this.class_name = class_name;
            this.confidence = confidence;
            this.top = top;
            this.left = left;
            this.bottom = bottom;
            this.right = right;
        }

        public static DetectionMsg Deserialize(MessageDeserializer deserializer) => new DetectionMsg(deserializer);

        private DetectionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.class_name);
            deserializer.Read(out this.confidence);
            deserializer.Read(out this.top);
            deserializer.Read(out this.left);
            deserializer.Read(out this.bottom);
            deserializer.Read(out this.right);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.class_name);
            serializer.Write(this.confidence);
            serializer.Write(this.top);
            serializer.Write(this.left);
            serializer.Write(this.bottom);
            serializer.Write(this.right);
        }

        public override string ToString()
        {
            return "DetectionMsg: " +
            "\nclass_name: " + class_name.ToString() +
            "\nconfidence: " + confidence.ToString() +
            "\ntop: " + top.ToString() +
            "\nleft: " + left.ToString() +
            "\nbottom: " + bottom.ToString() +
            "\nright: " + right.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
