//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class DetectionArrayMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/DetectionArray";
        public override string RosMessageName => k_RosMessageName;

        // Array of detected object
        public DetectionMsg[] detected_object;

        public DetectionArrayMsg()
        {
            this.detected_object = new DetectionMsg[0];
        }

        public DetectionArrayMsg(DetectionMsg[] detected_object)
        {
            this.detected_object = detected_object;
        }

        public static DetectionArrayMsg Deserialize(MessageDeserializer deserializer) => new DetectionArrayMsg(deserializer);

        private DetectionArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.detected_object, DetectionMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.detected_object);
            serializer.Write(this.detected_object);
        }

        public override string ToString()
        {
            return "DetectionArrayMsg: " +
            "\ndetected_object: " + System.String.Join(", ", detected_object.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
