//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class FaultWarningMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/FaultWarning";
        public override string RosMessageName => k_RosMessageName;

        //  severity definition
        public const byte Info = 0;
        public const byte Warning = 1;
        public const byte Error = 2;
        public const byte Critical = 3;
        public const byte AllGood = 4;
        //  topic definition
        public string Module;
        public byte Severity;
        public string Msg;

        public FaultWarningMsg()
        {
            this.Module = "";
            this.Severity = 0;
            this.Msg = "";
        }

        public FaultWarningMsg(string Module, byte Severity, string Msg)
        {
            this.Module = Module;
            this.Severity = Severity;
            this.Msg = Msg;
        }

        public static FaultWarningMsg Deserialize(MessageDeserializer deserializer) => new FaultWarningMsg(deserializer);

        private FaultWarningMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.Module);
            deserializer.Read(out this.Severity);
            deserializer.Read(out this.Msg);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.Module);
            serializer.Write(this.Severity);
            serializer.Write(this.Msg);
        }

        public override string ToString()
        {
            return "FaultWarningMsg: " +
            "\nModule: " + Module.ToString() +
            "\nSeverity: " + Severity.ToString() +
            "\nMsg: " + Msg.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
