//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class ImuInformationMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/ImuInformation";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.QuaternionMsg quaternion;
        public Geometry.AccelMsg acceleration;
        public Geometry.Vector3Msg magnetometer;

        public ImuInformationMsg()
        {
            this.quaternion = new Geometry.QuaternionMsg();
            this.acceleration = new Geometry.AccelMsg();
            this.magnetometer = new Geometry.Vector3Msg();
        }

        public ImuInformationMsg(Geometry.QuaternionMsg quaternion, Geometry.AccelMsg acceleration, Geometry.Vector3Msg magnetometer)
        {
            this.quaternion = quaternion;
            this.acceleration = acceleration;
            this.magnetometer = magnetometer;
        }

        public static ImuInformationMsg Deserialize(MessageDeserializer deserializer) => new ImuInformationMsg(deserializer);

        private ImuInformationMsg(MessageDeserializer deserializer)
        {
            this.quaternion = Geometry.QuaternionMsg.Deserialize(deserializer);
            this.acceleration = Geometry.AccelMsg.Deserialize(deserializer);
            this.magnetometer = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.quaternion);
            serializer.Write(this.acceleration);
            serializer.Write(this.magnetometer);
        }

        public override string ToString()
        {
            return "ImuInformationMsg: " +
            "\nquaternion: " + quaternion.ToString() +
            "\nacceleration: " + acceleration.ToString() +
            "\nmagnetometer: " + magnetometer.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
