//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class ModemUpdateMissionListMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/ModemUpdateMissionList";
        public override string RosMessageName => k_RosMessageName;

        public byte mission_id;
        public sbyte mission_state;

        public ModemUpdateMissionListMsg()
        {
            this.mission_id = 0;
            this.mission_state = 0;
        }

        public ModemUpdateMissionListMsg(byte mission_id, sbyte mission_state)
        {
            this.mission_id = mission_id;
            this.mission_state = mission_state;
        }

        public static ModemUpdateMissionListMsg Deserialize(MessageDeserializer deserializer) => new ModemUpdateMissionListMsg(deserializer);

        private ModemUpdateMissionListMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mission_id);
            deserializer.Read(out this.mission_state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mission_id);
            serializer.Write(this.mission_state);
        }

        public override string ToString()
        {
            return "ModemUpdateMissionListMsg: " +
            "\nmission_id: " + mission_id.ToString() +
            "\nmission_state: " + mission_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
