//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class MultiAddPoseMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/MultiAddPose";
        public override string RosMessageName => k_RosMessageName;

        public byte interpolation_method;
        public AddPoseMsg[] pose;

        public MultiAddPoseMsg()
        {
            this.interpolation_method = 0;
            this.pose = new AddPoseMsg[0];
        }

        public MultiAddPoseMsg(byte interpolation_method, AddPoseMsg[] pose)
        {
            this.interpolation_method = interpolation_method;
            this.pose = pose;
        }

        public static MultiAddPoseMsg Deserialize(MessageDeserializer deserializer) => new MultiAddPoseMsg(deserializer);

        private MultiAddPoseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.interpolation_method);
            deserializer.Read(out this.pose, AddPoseMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.interpolation_method);
            serializer.WriteLength(this.pose);
            serializer.Write(this.pose);
        }

        public override string ToString()
        {
            return "MultiAddPoseMsg: " +
            "\ninterpolation_method: " + interpolation_method.ToString() +
            "\npose: " + System.String.Join(", ", pose.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
