//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class ObstacleArrayMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/ObstacleArray";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public ObstacleInfoMsg[] obstacles;

        public ObstacleArrayMsg()
        {
            this.header = new HeaderMsg();
            this.obstacles = new ObstacleInfoMsg[0];
        }

        public ObstacleArrayMsg(HeaderMsg header, ObstacleInfoMsg[] obstacles)
        {
            this.header = header;
            this.obstacles = obstacles;
        }

        public static ObstacleArrayMsg Deserialize(MessageDeserializer deserializer) => new ObstacleArrayMsg(deserializer);

        private ObstacleArrayMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.obstacles, ObstacleInfoMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.obstacles);
            serializer.Write(this.obstacles);
        }

        public override string ToString()
        {
            return "ObstacleArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\nobstacles: " + System.String.Join(", ", obstacles.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
