//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class ObstacleInfoMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/ObstacleInfo";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public bool is_valid;
        public float confidence;
        public Geometry.PoseMsg pose;

        public ObstacleInfoMsg()
        {
            this.name = "";
            this.is_valid = false;
            this.confidence = 0.0f;
            this.pose = new Geometry.PoseMsg();
        }

        public ObstacleInfoMsg(string name, bool is_valid, float confidence, Geometry.PoseMsg pose)
        {
            this.name = name;
            this.is_valid = is_valid;
            this.confidence = confidence;
            this.pose = pose;
        }

        public static ObstacleInfoMsg Deserialize(MessageDeserializer deserializer) => new ObstacleInfoMsg(deserializer);

        private ObstacleInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.is_valid);
            deserializer.Read(out this.confidence);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.is_valid);
            serializer.Write(this.confidence);
            serializer.Write(this.pose);
        }

        public override string ToString()
        {
            return "ObstacleInfoMsg: " +
            "\nname: " + name.ToString() +
            "\nis_valid: " + is_valid.ToString() +
            "\nconfidence: " + confidence.ToString() +
            "\npose: " + pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
