//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class PingMsgMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/PingMsg";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double x;
        public double y;
        public double z;
        public ushort frequency;
        public double heading;
        public double elevation;
        public ushort debug;

        public PingMsgMsg()
        {
            this.header = new Std.HeaderMsg();
            this.x = 0.0;
            this.y = 0.0;
            this.z = 0.0;
            this.frequency = 0;
            this.heading = 0.0;
            this.elevation = 0.0;
            this.debug = 0;
        }

        public PingMsgMsg(Std.HeaderMsg header, double x, double y, double z, ushort frequency, double heading, double elevation, ushort debug)
        {
            this.header = header;
            this.x = x;
            this.y = y;
            this.z = z;
            this.frequency = frequency;
            this.heading = heading;
            this.elevation = elevation;
            this.debug = debug;
        }

        public static PingMsgMsg Deserialize(MessageDeserializer deserializer) => new PingMsgMsg(deserializer);

        private PingMsgMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.frequency);
            deserializer.Read(out this.heading);
            deserializer.Read(out this.elevation);
            deserializer.Read(out this.debug);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.frequency);
            serializer.Write(this.heading);
            serializer.Write(this.elevation);
            serializer.Write(this.debug);
        }

        public override string ToString()
        {
            return "PingMsgMsg: " +
            "\nheader: " + header.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\nfrequency: " + frequency.ToString() +
            "\nheading: " + heading.ToString() +
            "\nelevation: " + elevation.ToString() +
            "\ndebug: " + debug.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
