//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class PingMsgMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/PingMsg";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double phaseRef;
        public double phase1;
        public double phase2;
        public double phase3;
        public ushort frequency;
        public ushort debug;

        public PingMsgMsg()
        {
            this.header = new Std.HeaderMsg();
            this.phaseRef = 0.0;
            this.phase1 = 0.0;
            this.phase2 = 0.0;
            this.phase3 = 0.0;
            this.frequency = 0;
            this.debug = 0;
        }

        public PingMsgMsg(Std.HeaderMsg header, double phaseRef, double phase1, double phase2, double phase3, ushort frequency, ushort debug)
        {
            this.header = header;
            this.phaseRef = phaseRef;
            this.phase1 = phase1;
            this.phase2 = phase2;
            this.phase3 = phase3;
            this.frequency = frequency;
            this.debug = debug;
        }

        public static PingMsgMsg Deserialize(MessageDeserializer deserializer) => new PingMsgMsg(deserializer);

        private PingMsgMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.phaseRef);
            deserializer.Read(out this.phase1);
            deserializer.Read(out this.phase2);
            deserializer.Read(out this.phase3);
            deserializer.Read(out this.frequency);
            deserializer.Read(out this.debug);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.phaseRef);
            serializer.Write(this.phase1);
            serializer.Write(this.phase2);
            serializer.Write(this.phase3);
            serializer.Write(this.frequency);
            serializer.Write(this.debug);
        }

        public override string ToString()
        {
            return "PingMsgMsg: " +
            "\nheader: " + header.ToString() +
            "\nphaseRef: " + phaseRef.ToString() +
            "\nphase1: " + phase1.ToString() +
            "\nphase2: " + phase2.ToString() +
            "\nphase3: " + phase3.ToString() +
            "\nfrequency: " + frequency.ToString() +
            "\ndebug: " + debug.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
