//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class PingPoseMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/PingPose";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg pose;
        public byte frequency;
        public uint amplitude;
        public uint noise;

        public PingPoseMsg()
        {
            this.pose = new Geometry.PoseMsg();
            this.frequency = 0;
            this.amplitude = 0;
            this.noise = 0;
        }

        public PingPoseMsg(Geometry.PoseMsg pose, byte frequency, uint amplitude, uint noise)
        {
            this.pose = pose;
            this.frequency = frequency;
            this.amplitude = amplitude;
            this.noise = noise;
        }

        public static PingPoseMsg Deserialize(MessageDeserializer deserializer) => new PingPoseMsg(deserializer);

        private PingPoseMsg(MessageDeserializer deserializer)
        {
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.frequency);
            deserializer.Read(out this.amplitude);
            deserializer.Read(out this.noise);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose);
            serializer.Write(this.frequency);
            serializer.Write(this.amplitude);
            serializer.Write(this.noise);
        }

        public override string ToString()
        {
            return "PingPoseMsg: " +
            "\npose: " + pose.ToString() +
            "\nfrequency: " + frequency.ToString() +
            "\namplitude: " + amplitude.ToString() +
            "\nnoise: " + noise.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
