//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class PingAnglesMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/PingAngles";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double heading;
        public double elevation;
        public ushort frequency;
        public ushort snr;

        public PingAnglesMsg()
        {
            this.header = new Std.HeaderMsg();
            this.heading = 0.0;
            this.elevation = 0.0;
            this.frequency = 0;
            this.snr = 0;
        }

        public PingAnglesMsg(Std.HeaderMsg header, double heading, double elevation, ushort frequency, ushort snr)
        {
            this.header = header;
            this.heading = heading;
            this.elevation = elevation;
            this.frequency = frequency;
            this.snr = snr;
        }

        public static PingAnglesMsg Deserialize(MessageDeserializer deserializer) => new PingAnglesMsg(deserializer);

        private PingAnglesMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.heading);
            deserializer.Read(out this.elevation);
            deserializer.Read(out this.frequency);
            deserializer.Read(out this.snr);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.heading);
            serializer.Write(this.elevation);
            serializer.Write(this.frequency);
            serializer.Write(this.snr);
        }

        public override string ToString()
        {
            return "PingAnglesMsg: " +
            "\nheader: " + header.ToString() +
            "\nheading: " + heading.ToString() +
            "\nelevation: " + elevation.ToString() +
            "\nfrequency: " + frequency.ToString() +
            "\nsnr: " + snr.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
