//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class PointCloud2ExtendedMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/PointCloud2Extended";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public Sensor.PointCloud2Msg point_cloud2;
        public ushort sonar_id;
        public float range;
        public ushort gain;
        public float sos;

        public PointCloud2ExtendedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.point_cloud2 = new Sensor.PointCloud2Msg();
            this.sonar_id = 0;
            this.range = 0.0f;
            this.gain = 0;
            this.sos = 0.0f;
        }

        public PointCloud2ExtendedMsg(Std.HeaderMsg header, Sensor.PointCloud2Msg point_cloud2, ushort sonar_id, float range, ushort gain, float sos)
        {
            this.header = header;
            this.point_cloud2 = point_cloud2;
            this.sonar_id = sonar_id;
            this.range = range;
            this.gain = gain;
            this.sos = sos;
        }

        public static PointCloud2ExtendedMsg Deserialize(MessageDeserializer deserializer) => new PointCloud2ExtendedMsg(deserializer);

        private PointCloud2ExtendedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.point_cloud2 = Sensor.PointCloud2Msg.Deserialize(deserializer);
            deserializer.Read(out this.sonar_id);
            deserializer.Read(out this.range);
            deserializer.Read(out this.gain);
            deserializer.Read(out this.sos);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.point_cloud2);
            serializer.Write(this.sonar_id);
            serializer.Write(this.range);
            serializer.Write(this.gain);
            serializer.Write(this.sos);
        }

        public override string ToString()
        {
            return "PointCloud2ExtendedMsg: " +
            "\nheader: " + header.ToString() +
            "\npoint_cloud2: " + point_cloud2.ToString() +
            "\nsonar_id: " + sonar_id.ToString() +
            "\nrange: " + range.ToString() +
            "\ngain: " + gain.ToString() +
            "\nsos: " + sos.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
