//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class SendRS485MsgMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/SendRS485Msg";
        public override string RosMessageName => k_RosMessageName;

        //  SLAVE ID
        public const byte SLAVE_PSU0 = 0;
        public const byte SLAVE_PSU1 = 1;
        public const byte SLAVE_PSU2 = 2;
        public const byte SLAVE_PSU3 = 3;
        public const byte SLAVE_KILLMISSION = 4;
        public const byte SLAVE_ESC = 5;
        public const byte SLAVE_IO = 6;
        public const byte SLAVE_STATE_SCREEN = 7;
        public const byte SLAVE_PWR_MANAGEMENT = 8;
        // CMD
        //  les define de la kill mission switch
        public const byte CMD_MISSION = 0;
        public const byte CMD_KILL = 1;
        //  les define de la backplane/PSU
        public const byte CMD_VOLTAGE = 0;
        public const byte CMD_CURRENT = 1;
        //  les define de la backplane/ESC
        public const byte CMD_READ_MOTOR = 15;
        public const byte CMD_ACT_MOTOR = 16;
        public const byte CMD_PWM = 17;
        //  define IO CONTROL
        public const byte CMD_IO_TEMP = 0;
        public const byte CMD_IO_DROPPER_ACTION = 1;
        public const byte CMD_IO_TORPEDO_ACTION = 2;
        public const byte CMD_IO_ARM_ACTION = 3;
        public const byte CMD_IO_LEAK_SENSOR = 4;
        //  DATA
        //  define IO CONTROL
        public const byte DATA_IO_DROPPER_PORT = 0;
        public const byte DATA_IO_DROPPER_STARBOARD = 1;
        public const byte DATA_IO_TORPEDO_PORT = 0;
        public const byte DATA_IO_TORPEDO_STARBOARD = 1;
        public const byte DATA_IO_ARM_CLOSE = 0;
        public const byte DATA_IO_ARM_OPEN = 1;
        public const byte DATA_IO_LEAK_SENSOR_DRY = 0;
        public const byte DATA_IO_LEAK_SENSOR_LEAK = 1;
        //  SERVICE DEFINITION
        public byte slave;
        public byte cmd;
        public byte[] data;

        public SendRS485MsgMsg()
        {
            this.slave = 0;
            this.cmd = 0;
            this.data = new byte[0];
        }

        public SendRS485MsgMsg(byte slave, byte cmd, byte[] data)
        {
            this.slave = slave;
            this.cmd = cmd;
            this.data = data;
        }

        public static SendRS485MsgMsg Deserialize(MessageDeserializer deserializer) => new SendRS485MsgMsg(deserializer);

        private SendRS485MsgMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.slave);
            deserializer.Read(out this.cmd);
            deserializer.Read(out this.data, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.slave);
            serializer.Write(this.cmd);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "SendRS485MsgMsg: " +
            "\nslave: " + slave.ToString() +
            "\ncmd: " + cmd.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
