//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class VisionTargetMsg : Message
    {
        public const string k_RosMessageName = "sonia_common/VisionTarget";
        public override string RosMessageName => k_RosMessageName;

        public string header;
        public float x;
        public float y;
        public float width;
        public float height;
        public float angle;
        public string desc_1;
        public string desc_2;

        public VisionTargetMsg()
        {
            this.header = "";
            this.x = 0.0f;
            this.y = 0.0f;
            this.width = 0.0f;
            this.height = 0.0f;
            this.angle = 0.0f;
            this.desc_1 = "";
            this.desc_2 = "";
        }

        public VisionTargetMsg(string header, float x, float y, float width, float height, float angle, string desc_1, string desc_2)
        {
            this.header = header;
            this.x = x;
            this.y = y;
            this.width = width;
            this.height = height;
            this.angle = angle;
            this.desc_1 = desc_1;
            this.desc_2 = desc_2;
        }

        public static VisionTargetMsg Deserialize(MessageDeserializer deserializer) => new VisionTargetMsg(deserializer);

        private VisionTargetMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.header);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.width);
            deserializer.Read(out this.height);
            deserializer.Read(out this.angle);
            deserializer.Read(out this.desc_1);
            deserializer.Read(out this.desc_2);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.width);
            serializer.Write(this.height);
            serializer.Write(this.angle);
            serializer.Write(this.desc_1);
            serializer.Write(this.desc_2);
        }

        public override string ToString()
        {
            return "VisionTargetMsg: " +
            "\nheader: " + header.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nwidth: " + width.ToString() +
            "\nheight: " + height.ToString() +
            "\nangle: " + angle.ToString() +
            "\ndesc_1: " + desc_1.ToString() +
            "\ndesc_2: " + desc_2.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
