//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommonRos2
{
    [Serializable]
    public class BatteryPowerMessagesMsg : Message
    {
        public const string k_RosMessageName = "sonia_common_ros2/BatteryPowerMessages";
        public override string RosMessageName => k_RosMessageName;

        public float battery1;
        public float battery2;

        public BatteryPowerMessagesMsg()
        {
            this.battery1 = 0.0f;
            this.battery2 = 0.0f;
        }

        public BatteryPowerMessagesMsg(float battery1, float battery2)
        {
            this.battery1 = battery1;
            this.battery2 = battery2;
        }

        public static BatteryPowerMessagesMsg Deserialize(MessageDeserializer deserializer) => new BatteryPowerMessagesMsg(deserializer);

        private BatteryPowerMessagesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.battery1);
            deserializer.Read(out this.battery2);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.battery1);
            serializer.Write(this.battery2);
        }

        public override string ToString()
        {
            return "BatteryPowerMessagesMsg: " +
            "\nbattery1: " + battery1.ToString() +
            "\nbattery2: " + battery2.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
