//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommonRos2
{
    [Serializable]
    public class BodyVelocityDVLMsg : Message
    {
        public const string k_RosMessageName = "sonia_common_ros2/BodyVelocityDVL";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double x_vel_btm;
        public double y_vel_btm;
        public double z_vel_btm;
        public double e_vel_btm;
        public double velocity1;
        public double velocity2;
        public double velocity3;
        public double velocity4;

        public BodyVelocityDVLMsg()
        {
            this.header = new Std.HeaderMsg();
            this.x_vel_btm = 0.0;
            this.y_vel_btm = 0.0;
            this.z_vel_btm = 0.0;
            this.e_vel_btm = 0.0;
            this.velocity1 = 0.0;
            this.velocity2 = 0.0;
            this.velocity3 = 0.0;
            this.velocity4 = 0.0;
        }

        public BodyVelocityDVLMsg(Std.HeaderMsg header, double x_vel_btm, double y_vel_btm, double z_vel_btm, double e_vel_btm, double velocity1, double velocity2, double velocity3, double velocity4)
        {
            this.header = header;
            this.x_vel_btm = x_vel_btm;
            this.y_vel_btm = y_vel_btm;
            this.z_vel_btm = z_vel_btm;
            this.e_vel_btm = e_vel_btm;
            this.velocity1 = velocity1;
            this.velocity2 = velocity2;
            this.velocity3 = velocity3;
            this.velocity4 = velocity4;
        }

        public static BodyVelocityDVLMsg Deserialize(MessageDeserializer deserializer) => new BodyVelocityDVLMsg(deserializer);

        private BodyVelocityDVLMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.x_vel_btm);
            deserializer.Read(out this.y_vel_btm);
            deserializer.Read(out this.z_vel_btm);
            deserializer.Read(out this.e_vel_btm);
            deserializer.Read(out this.velocity1);
            deserializer.Read(out this.velocity2);
            deserializer.Read(out this.velocity3);
            deserializer.Read(out this.velocity4);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.x_vel_btm);
            serializer.Write(this.y_vel_btm);
            serializer.Write(this.z_vel_btm);
            serializer.Write(this.e_vel_btm);
            serializer.Write(this.velocity1);
            serializer.Write(this.velocity2);
            serializer.Write(this.velocity3);
            serializer.Write(this.velocity4);
        }

        public override string ToString()
        {
            return "BodyVelocityDVLMsg: " +
            "\nheader: " + header.ToString() +
            "\nx_vel_btm: " + x_vel_btm.ToString() +
            "\ny_vel_btm: " + y_vel_btm.ToString() +
            "\nz_vel_btm: " + z_vel_btm.ToString() +
            "\ne_vel_btm: " + e_vel_btm.ToString() +
            "\nvelocity1: " + velocity1.ToString() +
            "\nvelocity2: " + velocity2.ToString() +
            "\nvelocity3: " + velocity3.ToString() +
            "\nvelocity4: " + velocity4.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
