//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommonRos2
{
    [Serializable]
    public class MissionStatusMsg : Message
    {
        public const string k_RosMessageName = "sonia_common_ros2/MissionStatus";
        public override string RosMessageName => k_RosMessageName;

        public bool status;

        public MissionStatusMsg()
        {
            this.status = false;
        }

        public MissionStatusMsg(bool status)
        {
            this.status = status;
        }

        public static MissionStatusMsg Deserialize(MessageDeserializer deserializer) => new MissionStatusMsg(deserializer);

        private MissionStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "MissionStatusMsg: " +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
