//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommonRos2
{
    [Serializable]
    public class MotorPowerMessagesMsg : Message
    {
        public const string k_RosMessageName = "sonia_common_ros2/MotorPowerMessages";
        public override string RosMessageName => k_RosMessageName;

        public float motor1;
        public float motor2;
        public float motor3;
        public float motor4;
        public float motor5;
        public float motor6;
        public float motor7;
        public float motor8;

        public MotorPowerMessagesMsg()
        {
            this.motor1 = 0.0f;
            this.motor2 = 0.0f;
            this.motor3 = 0.0f;
            this.motor4 = 0.0f;
            this.motor5 = 0.0f;
            this.motor6 = 0.0f;
            this.motor7 = 0.0f;
            this.motor8 = 0.0f;
        }

        public MotorPowerMessagesMsg(float motor1, float motor2, float motor3, float motor4, float motor5, float motor6, float motor7, float motor8)
        {
            this.motor1 = motor1;
            this.motor2 = motor2;
            this.motor3 = motor3;
            this.motor4 = motor4;
            this.motor5 = motor5;
            this.motor6 = motor6;
            this.motor7 = motor7;
            this.motor8 = motor8;
        }

        public static MotorPowerMessagesMsg Deserialize(MessageDeserializer deserializer) => new MotorPowerMessagesMsg(deserializer);

        private MotorPowerMessagesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.motor1);
            deserializer.Read(out this.motor2);
            deserializer.Read(out this.motor3);
            deserializer.Read(out this.motor4);
            deserializer.Read(out this.motor5);
            deserializer.Read(out this.motor6);
            deserializer.Read(out this.motor7);
            deserializer.Read(out this.motor8);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.motor1);
            serializer.Write(this.motor2);
            serializer.Write(this.motor3);
            serializer.Write(this.motor4);
            serializer.Write(this.motor5);
            serializer.Write(this.motor6);
            serializer.Write(this.motor7);
            serializer.Write(this.motor8);
        }

        public override string ToString()
        {
            return "MotorPowerMessagesMsg: " +
            "\nmotor1: " + motor1.ToString() +
            "\nmotor2: " + motor2.ToString() +
            "\nmotor3: " + motor3.ToString() +
            "\nmotor4: " + motor4.ToString() +
            "\nmotor5: " + motor5.ToString() +
            "\nmotor6: " + motor6.ToString() +
            "\nmotor7: " + motor7.ToString() +
            "\nmotor8: " + motor8.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
