//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommonRos2
{
    [Serializable]
    public class MotorFeedbackMsg : Message
    {
        public const string k_RosMessageName = "sonia_common_ros2/MotorFeedback";
        public override string RosMessageName => k_RosMessageName;

        public byte motor1;
        public byte motor2;
        public byte motor3;
        public byte motor4;
        public byte motor5;
        public byte motor6;
        public byte motor7;
        public byte motor8;

        public MotorFeedbackMsg()
        {
            this.motor1 = 0;
            this.motor2 = 0;
            this.motor3 = 0;
            this.motor4 = 0;
            this.motor5 = 0;
            this.motor6 = 0;
            this.motor7 = 0;
            this.motor8 = 0;
        }

        public MotorFeedbackMsg(byte motor1, byte motor2, byte motor3, byte motor4, byte motor5, byte motor6, byte motor7, byte motor8)
        {
            this.motor1 = motor1;
            this.motor2 = motor2;
            this.motor3 = motor3;
            this.motor4 = motor4;
            this.motor5 = motor5;
            this.motor6 = motor6;
            this.motor7 = motor7;
            this.motor8 = motor8;
        }

        public static MotorFeedbackMsg Deserialize(MessageDeserializer deserializer) => new MotorFeedbackMsg(deserializer);

        private MotorFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.motor1);
            deserializer.Read(out this.motor2);
            deserializer.Read(out this.motor3);
            deserializer.Read(out this.motor4);
            deserializer.Read(out this.motor5);
            deserializer.Read(out this.motor6);
            deserializer.Read(out this.motor7);
            deserializer.Read(out this.motor8);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.motor1);
            serializer.Write(this.motor2);
            serializer.Write(this.motor3);
            serializer.Write(this.motor4);
            serializer.Write(this.motor5);
            serializer.Write(this.motor6);
            serializer.Write(this.motor7);
            serializer.Write(this.motor8);
        }

        public override string ToString()
        {
            return "MotorFeedbackMsg: " +
            "\nmotor1: " + motor1.ToString() +
            "\nmotor2: " + motor2.ToString() +
            "\nmotor3: " + motor3.ToString() +
            "\nmotor4: " + motor4.ToString() +
            "\nmotor5: " + motor5.ToString() +
            "\nmotor6: " + motor6.ToString() +
            "\nmotor7: " + motor7.ToString() +
            "\nmotor8: " + motor8.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
