//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommonRos2
{
    [Serializable]
    public class MpcGainsMsg : Message
    {
        public const string k_RosMessageName = "sonia_common_ros2/MpcGains";
        public override string RosMessageName => k_RosMessageName;

        public double[] ov;
        public double[] mv;
        public double[] mvr;
        public double max_thrust;
        public double min_thrust;

        public MpcGainsMsg()
        {
            this.ov = new double[0];
            this.mv = new double[0];
            this.mvr = new double[0];
            this.max_thrust = 0.0;
            this.min_thrust = 0.0;
        }

        public MpcGainsMsg(double[] ov, double[] mv, double[] mvr, double max_thrust, double min_thrust)
        {
            this.ov = ov;
            this.mv = mv;
            this.mvr = mvr;
            this.max_thrust = max_thrust;
            this.min_thrust = min_thrust;
        }

        public static MpcGainsMsg Deserialize(MessageDeserializer deserializer) => new MpcGainsMsg(deserializer);

        private MpcGainsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ov, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.mv, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.mvr, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.max_thrust);
            deserializer.Read(out this.min_thrust);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.ov);
            serializer.Write(this.ov);
            serializer.WriteLength(this.mv);
            serializer.Write(this.mv);
            serializer.WriteLength(this.mvr);
            serializer.Write(this.mvr);
            serializer.Write(this.max_thrust);
            serializer.Write(this.min_thrust);
        }

        public override string ToString()
        {
            return "MpcGainsMsg: " +
            "\nov: " + System.String.Join(", ", ov.ToList()) +
            "\nmv: " + System.String.Join(", ", mv.ToList()) +
            "\nmvr: " + System.String.Join(", ", mvr.ToList()) +
            "\nmax_thrust: " + max_thrust.ToString() +
            "\nmin_thrust: " + min_thrust.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
