//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommonRos2
{
    [Serializable]
    public class PoseArrayMsg : Message
    {
        public const string k_RosMessageName = "sonia_common_ros2/PoseArray";
        public override string RosMessageName => k_RosMessageName;

        //  Options for Interpolation method
        public const byte INTERPOLATION_HERMITE = 0;
        public const byte INTERPOLATION_V5CUBIC = 1;
        public const byte INTERPOLATION_SPLINE = 2;
        public byte interpolation_method;
        public PoseMsg[] poses;

        public PoseArrayMsg()
        {
            this.interpolation_method = 0;
            this.poses = new PoseMsg[0];
        }

        public PoseArrayMsg(byte interpolation_method, PoseMsg[] poses)
        {
            this.interpolation_method = interpolation_method;
            this.poses = poses;
        }

        public static PoseArrayMsg Deserialize(MessageDeserializer deserializer) => new PoseArrayMsg(deserializer);

        private PoseArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.interpolation_method);
            deserializer.Read(out this.poses, PoseMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.interpolation_method);
            serializer.WriteLength(this.poses);
            serializer.Write(this.poses);
        }

        public override string ToString()
        {
            return "PoseArrayMsg: " +
            "\ninterpolation_method: " + interpolation_method.ToString() +
            "\nposes: " + System.String.Join(", ", poses.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
