//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommonRos2
{
    [Serializable]
    public class PoseMsg : Message
    {
        public const string k_RosMessageName = "sonia_common_ros2/Pose";
        public override string RosMessageName => k_RosMessageName;

        //  Options for frame
        public const byte FRAME_ABS_POS_ABS_ANG = 0;
        public const byte FRAME_REL_POS_REL_ANG = 1;
        public const byte FRAME_REL_POS_ABS_ANG = 2;
        public const byte FRAME_ABS_POS_REL_ANG = 3;
        public const byte FRAME_ABS_DEPTH_REL_OTHER = 4;
        //  Options for speed
        public const byte SPEED_NORMAL = 0;
        public const byte SPEED_FAST = 1;
        public const byte SPEED_SLOW = 2;
        public byte frame;
        public byte speed;
        public Geometry.PointMsg position;
        public Geometry.Vector3Msg orientation;
        public double fine;
        //  Precision of movement
        public bool rotation;
        //  Determine if the rotation is full path or short path.

        public PoseMsg()
        {
            this.frame = 0;
            this.speed = 0;
            this.position = new Geometry.PointMsg();
            this.orientation = new Geometry.Vector3Msg();
            this.fine = 0.0;
            this.rotation = false;
        }

        public PoseMsg(byte frame, byte speed, Geometry.PointMsg position, Geometry.Vector3Msg orientation, double fine, bool rotation)
        {
            this.frame = frame;
            this.speed = speed;
            this.position = position;
            this.orientation = orientation;
            this.fine = fine;
            this.rotation = rotation;
        }

        public static PoseMsg Deserialize(MessageDeserializer deserializer) => new PoseMsg(deserializer);

        private PoseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.frame);
            deserializer.Read(out this.speed);
            this.position = Geometry.PointMsg.Deserialize(deserializer);
            this.orientation = Geometry.Vector3Msg.Deserialize(deserializer);
            deserializer.Read(out this.fine);
            deserializer.Read(out this.rotation);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.frame);
            serializer.Write(this.speed);
            serializer.Write(this.position);
            serializer.Write(this.orientation);
            serializer.Write(this.fine);
            serializer.Write(this.rotation);
        }

        public override string ToString()
        {
            return "PoseMsg: " +
            "\nframe: " + frame.ToString() +
            "\nspeed: " + speed.ToString() +
            "\nposition: " + position.ToString() +
            "\norientation: " + orientation.ToString() +
            "\nfine: " + fine.ToString() +
            "\nrotation: " + rotation.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
