//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommonRos2
{
    [Serializable]
    public class SerialMessageMsg : Message
    {
        public const string k_RosMessageName = "sonia_common_ros2/SerialMessage";
        public override string RosMessageName => k_RosMessageName;

        public sbyte id;
        public int size;
        public sbyte[] msg;

        public SerialMessageMsg()
        {
            this.id = 0;
            this.size = 0;
            this.msg = new sbyte[0];
        }

        public SerialMessageMsg(sbyte id, int size, sbyte[] msg)
        {
            this.id = id;
            this.size = size;
            this.msg = msg;
        }

        public static SerialMessageMsg Deserialize(MessageDeserializer deserializer) => new SerialMessageMsg(deserializer);

        private SerialMessageMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.size);
            deserializer.Read(out this.msg, sizeof(sbyte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.size);
            serializer.WriteLength(this.msg);
            serializer.Write(this.msg);
        }

        public override string ToString()
        {
            return "SerialMessageMsg: " +
            "\nid: " + id.ToString() +
            "\nsize: " + size.ToString() +
            "\nmsg: " + System.String.Join(", ", msg.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
