//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommonRos2
{
    [Serializable]
    public class UnderwaterComMsg : Message
    {
        public const string k_RosMessageName = "sonia_common_ros2/UnderwaterCom";
        public override string RosMessageName => k_RosMessageName;

        public ulong data;

        public UnderwaterComMsg()
        {
            this.data = 0;
        }

        public UnderwaterComMsg(ulong data)
        {
            this.data = data;
        }

        public static UnderwaterComMsg Deserialize(MessageDeserializer deserializer) => new UnderwaterComMsg(deserializer);

        private UnderwaterComMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "UnderwaterComMsg: " +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
