//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class ActuatorDoActionSrvRequest : Message
    {
        public const string k_RosMessageName = "sonia_common/ActuatorDoActionSrv";
        public override string RosMessageName => k_RosMessageName;

        public const byte ELEMENT_TORPEDO = 0;
        public const byte ELEMENT_DROPPER = 1;
        public const byte ELEMENT_ARM = 2;
        public const byte SIDE_PORT = 0;
        public const byte SIDE_STARBOARD = 1;
        public const byte ARM_CLOSE = 0;
        public const byte ARM_OPEN = 1;
        public const byte ACTION_TORPEDO_RESET = 0;
        public const byte ACTION_TORPEDO_ARMED = 1;
        public const byte ACTION_TORPEDO_LAUNCH = 1;
        public const byte ACTION_DROPPER_RESET = 0;
        public const byte ACTION_DROPPER_LAUNCH = 1;
        public const byte ACTION_ARM_EXEC = 1;
        public byte element;
        public byte side;
        public byte action;

        public ActuatorDoActionSrvRequest()
        {
            this.element = 0;
            this.side = 0;
            this.action = 0;
        }

        public ActuatorDoActionSrvRequest(byte element, byte side, byte action)
        {
            this.element = element;
            this.side = side;
            this.action = action;
        }

        public static ActuatorDoActionSrvRequest Deserialize(MessageDeserializer deserializer) => new ActuatorDoActionSrvRequest(deserializer);

        private ActuatorDoActionSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.element);
            deserializer.Read(out this.side);
            deserializer.Read(out this.action);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.element);
            serializer.Write(this.side);
            serializer.Write(this.action);
        }

        public override string ToString()
        {
            return "ActuatorDoActionSrvRequest: " +
            "\nelement: " + element.ToString() +
            "\nside: " + side.ToString() +
            "\naction: " + action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
