//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class AddOffsetResponse : Message
    {
        public const string k_RosMessageName = "sonia_common/AddOffset";
        public override string RosMessageName => k_RosMessageName;

        public double total_offset;

        public AddOffsetResponse()
        {
            this.total_offset = 0.0;
        }

        public AddOffsetResponse(double total_offset)
        {
            this.total_offset = total_offset;
        }

        public static AddOffsetResponse Deserialize(MessageDeserializer deserializer) => new AddOffsetResponse(deserializer);

        private AddOffsetResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.total_offset);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.total_offset);
        }

        public override string ToString()
        {
            return "AddOffsetResponse: " +
            "\ntotal_offset: " + total_offset.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
