//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class ChangeNetworkResponse : Message
    {
        public const string k_RosMessageName = "sonia_common/ChangeNetwork";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public ChangeNetworkResponse()
        {
            this.success = false;
        }

        public ChangeNetworkResponse(bool success)
        {
            this.success = success;
        }

        public static ChangeNetworkResponse Deserialize(MessageDeserializer deserializer) => new ChangeNetworkResponse(deserializer);

        private ChangeNetworkResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "ChangeNetworkResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
