//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class CopyFilterchainRequest : Message
    {
        public const string k_RosMessageName = "sonia_common/CopyFilterchain";
        public override string RosMessageName => k_RosMessageName;

        //  Create a new filtechain in a list, copied from a another one
        public string filterchain_to_copy;
        public string filterchain_new_name;

        public CopyFilterchainRequest()
        {
            this.filterchain_to_copy = "";
            this.filterchain_new_name = "";
        }

        public CopyFilterchainRequest(string filterchain_to_copy, string filterchain_new_name)
        {
            this.filterchain_to_copy = filterchain_to_copy;
            this.filterchain_new_name = filterchain_new_name;
        }

        public static CopyFilterchainRequest Deserialize(MessageDeserializer deserializer) => new CopyFilterchainRequest(deserializer);

        private CopyFilterchainRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.filterchain_to_copy);
            deserializer.Read(out this.filterchain_new_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.filterchain_to_copy);
            serializer.Write(this.filterchain_new_name);
        }

        public override string ToString()
        {
            return "CopyFilterchainRequest: " +
            "\nfilterchain_to_copy: " + filterchain_to_copy.ToString() +
            "\nfilterchain_new_name: " + filterchain_new_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
