//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class CopyFilterchainResponse : Message
    {
        public const string k_RosMessageName = "sonia_common/CopyFilterchain";
        public override string RosMessageName => k_RosMessageName;

        public const byte SUCCESS = 1;
        public const byte FAIL = 0;
        //  boolean, 1 success, 0 fail.
        public byte success;

        public CopyFilterchainResponse()
        {
            this.success = 0;
        }

        public CopyFilterchainResponse(byte success)
        {
            this.success = success;
        }

        public static CopyFilterchainResponse Deserialize(MessageDeserializer deserializer) => new CopyFilterchainResponse(deserializer);

        private CopyFilterchainResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "CopyFilterchainResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
