//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class ExecuteCmdRequest : Message
    {
        public const string k_RosMessageName = "sonia_common/ExecuteCmd";
        public override string RosMessageName => k_RosMessageName;

        // Command to start/stop DetectionTask
        public const byte START = 1;
        public const byte STOP = 2;
        public string node_name;
        public string filterchain_name;
        public string media_name;
        // the defined up there.
        public byte cmd;

        public ExecuteCmdRequest()
        {
            this.node_name = "";
            this.filterchain_name = "";
            this.media_name = "";
            this.cmd = 0;
        }

        public ExecuteCmdRequest(string node_name, string filterchain_name, string media_name, byte cmd)
        {
            this.node_name = node_name;
            this.filterchain_name = filterchain_name;
            this.media_name = media_name;
            this.cmd = cmd;
        }

        public static ExecuteCmdRequest Deserialize(MessageDeserializer deserializer) => new ExecuteCmdRequest(deserializer);

        private ExecuteCmdRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.node_name);
            deserializer.Read(out this.filterchain_name);
            deserializer.Read(out this.media_name);
            deserializer.Read(out this.cmd);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.node_name);
            serializer.Write(this.filterchain_name);
            serializer.Write(this.media_name);
            serializer.Write(this.cmd);
        }

        public override string ToString()
        {
            return "ExecuteCmdRequest: " +
            "\nnode_name: " + node_name.ToString() +
            "\nfilterchain_name: " + filterchain_name.ToString() +
            "\nmedia_name: " + media_name.ToString() +
            "\ncmd: " + cmd.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
