//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class ExecuteCmdResponse : Message
    {
        public const string k_RosMessageName = "sonia_common/ExecuteCmd";
        public override string RosMessageName => k_RosMessageName;

        public string response;

        public ExecuteCmdResponse()
        {
            this.response = "";
        }

        public ExecuteCmdResponse(string response)
        {
            this.response = response;
        }

        public static ExecuteCmdResponse Deserialize(MessageDeserializer deserializer) => new ExecuteCmdResponse(deserializer);

        private ExecuteCmdResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.response);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.response);
        }

        public override string ToString()
        {
            return "ExecuteCmdResponse: " +
            "\nresponse: " + response.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
