//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class GetAvailableCamerasRequest : Message
    {
        public const string k_RosMessageName = "sonia_common/GetAvailableCameras";
        public override string RosMessageName => k_RosMessageName;


        public GetAvailableCamerasRequest()
        {
        }
        public static GetAvailableCamerasRequest Deserialize(MessageDeserializer deserializer) => new GetAvailableCamerasRequest(deserializer);

        private GetAvailableCamerasRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetAvailableCamerasRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
