//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class GetCameraFeaturesResponse : Message
    {
        public const string k_RosMessageName = "sonia_common/GetCameraFeatures";
        public override string RosMessageName => k_RosMessageName;

        public string feature_value;
        public uint feature_type;

        public GetCameraFeaturesResponse()
        {
            this.feature_value = "";
            this.feature_type = 0;
        }

        public GetCameraFeaturesResponse(string feature_value, uint feature_type)
        {
            this.feature_value = feature_value;
            this.feature_type = feature_type;
        }

        public static GetCameraFeaturesResponse Deserialize(MessageDeserializer deserializer) => new GetCameraFeaturesResponse(deserializer);

        private GetCameraFeaturesResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.feature_value);
            deserializer.Read(out this.feature_type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.feature_value);
            serializer.Write(this.feature_type);
        }

        public override string ToString()
        {
            return "GetCameraFeaturesResponse: " +
            "\nfeature_value: " + feature_value.ToString() +
            "\nfeature_type: " + feature_type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
