//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class GetFilterchainFilterRequest : Message
    {
        public const string k_RosMessageName = "sonia_common/GetFilterchainFilter";
        public override string RosMessageName => k_RosMessageName;

        //  Provide the list of filter on an execution or a filterchain
        //  Give list for an execution
        public string exec_name;
        //  Give list for a register filterchain if
        //  no exec provided
        public string filterchain;

        public GetFilterchainFilterRequest()
        {
            this.exec_name = "";
            this.filterchain = "";
        }

        public GetFilterchainFilterRequest(string exec_name, string filterchain)
        {
            this.exec_name = exec_name;
            this.filterchain = filterchain;
        }

        public static GetFilterchainFilterRequest Deserialize(MessageDeserializer deserializer) => new GetFilterchainFilterRequest(deserializer);

        private GetFilterchainFilterRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.exec_name);
            deserializer.Read(out this.filterchain);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.exec_name);
            serializer.Write(this.filterchain);
        }

        public override string ToString()
        {
            return "GetFilterchainFilterRequest: " +
            "\nexec_name: " + exec_name.ToString() +
            "\nfilterchain: " + filterchain.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
