//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class GetFilterchainFilterParamResponse : Message
    {
        public const string k_RosMessageName = "sonia_common/GetFilterchainFilterParam";
        public override string RosMessageName => k_RosMessageName;

        //  form: paramName1,type,val
        public string list;

        public GetFilterchainFilterParamResponse()
        {
            this.list = "";
        }

        public GetFilterchainFilterParamResponse(string list)
        {
            this.list = list;
        }

        public static GetFilterchainFilterParamResponse Deserialize(MessageDeserializer deserializer) => new GetFilterchainFilterParamResponse(deserializer);

        private GetFilterchainFilterParamResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.list);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.list);
        }

        public override string ToString()
        {
            return "GetFilterchainFilterParamResponse: " +
            "\nlist: " + list.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
