//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class GetFilterchainFilterParamRequest : Message
    {
        public const string k_RosMessageName = "sonia_common/GetFilterchainFilterParam";
        public override string RosMessageName => k_RosMessageName;

        //  Returns the info about a single parameter for a filter
        //  Exec to get params from (might be different from those in xml)
        public string exec_name;
        //  Filterchain, if exec null, to get params from
        public string filterchain;
        //  Filter which hold those parameters
        public string filter;
        //  the parameter we want info on.
        public string parameter;

        public GetFilterchainFilterParamRequest()
        {
            this.exec_name = "";
            this.filterchain = "";
            this.filter = "";
            this.parameter = "";
        }

        public GetFilterchainFilterParamRequest(string exec_name, string filterchain, string filter, string parameter)
        {
            this.exec_name = exec_name;
            this.filterchain = filterchain;
            this.filter = filter;
            this.parameter = parameter;
        }

        public static GetFilterchainFilterParamRequest Deserialize(MessageDeserializer deserializer) => new GetFilterchainFilterParamRequest(deserializer);

        private GetFilterchainFilterParamRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.exec_name);
            deserializer.Read(out this.filterchain);
            deserializer.Read(out this.filter);
            deserializer.Read(out this.parameter);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.exec_name);
            serializer.Write(this.filterchain);
            serializer.Write(this.filter);
            serializer.Write(this.parameter);
        }

        public override string ToString()
        {
            return "GetFilterchainFilterParamRequest: " +
            "\nexec_name: " + exec_name.ToString() +
            "\nfilterchain: " + filterchain.ToString() +
            "\nfilter: " + filter.ToString() +
            "\nparameter: " + parameter.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
