//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class GetFilterchainFilterAllParamRequest : Message
    {
        public const string k_RosMessageName = "sonia_common/GetFilterchainFilterAllParam";
        public override string RosMessageName => k_RosMessageName;

        //  Returns a list of parameter for a filter
        //  Exec to get params from (might be different from those in xml)
        public string exec_name;
        //  Filterchain, if exec null, to get params from
        public string filterchain;
        //  Filter which hold those parameters
        public string filter;

        public GetFilterchainFilterAllParamRequest()
        {
            this.exec_name = "";
            this.filterchain = "";
            this.filter = "";
        }

        public GetFilterchainFilterAllParamRequest(string exec_name, string filterchain, string filter)
        {
            this.exec_name = exec_name;
            this.filterchain = filterchain;
            this.filter = filter;
        }

        public static GetFilterchainFilterAllParamRequest Deserialize(MessageDeserializer deserializer) => new GetFilterchainFilterAllParamRequest(deserializer);

        private GetFilterchainFilterAllParamRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.exec_name);
            deserializer.Read(out this.filterchain);
            deserializer.Read(out this.filter);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.exec_name);
            serializer.Write(this.filterchain);
            serializer.Write(this.filter);
        }

        public override string ToString()
        {
            return "GetFilterchainFilterAllParamRequest: " +
            "\nexec_name: " + exec_name.ToString() +
            "\nfilterchain: " + filterchain.ToString() +
            "\nfilter: " + filter.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
