//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class GetInformationListRequest : Message
    {
        public const string k_RosMessageName = "sonia_common/GetInformationList";
        public override string RosMessageName => k_RosMessageName;

        //  Provide an interface to list different object of the server
        // return the execution list
        public const byte EXEC = 1;
        // return the media list
        public const byte MEDIA = 2;
        // return the filterchain list
        public const byte FILTERCHAIN = 3;
        // return the filter list
        public const byte FILTERS = 4;
        public byte cmd;

        public GetInformationListRequest()
        {
            this.cmd = 0;
        }

        public GetInformationListRequest(byte cmd)
        {
            this.cmd = cmd;
        }

        public static GetInformationListRequest Deserialize(MessageDeserializer deserializer) => new GetInformationListRequest(deserializer);

        private GetInformationListRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cmd);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cmd);
        }

        public override string ToString()
        {
            return "GetInformationListRequest: " +
            "\ncmd: " + cmd.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
