//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class GetMediaFromExecutionRequest : Message
    {
        public const string k_RosMessageName = "sonia_common/GetMediaFromExecution";
        public override string RosMessageName => k_RosMessageName;

        //  Provide the of media on an execution
        //  Give list for an execution
        public string exec_name;

        public GetMediaFromExecutionRequest()
        {
            this.exec_name = "";
        }

        public GetMediaFromExecutionRequest(string exec_name)
        {
            this.exec_name = exec_name;
        }

        public static GetMediaFromExecutionRequest Deserialize(MessageDeserializer deserializer) => new GetMediaFromExecutionRequest(deserializer);

        private GetMediaFromExecutionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.exec_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.exec_name);
        }

        public override string ToString()
        {
            return "GetMediaFromExecutionRequest: " +
            "\nexec_name: " + exec_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
