//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class GetMediaFromExecutionResponse : Message
    {
        public const string k_RosMessageName = "sonia_common/GetMediaFromExecution";
        public override string RosMessageName => k_RosMessageName;

        public string list;

        public GetMediaFromExecutionResponse()
        {
            this.list = "";
        }

        public GetMediaFromExecutionResponse(string list)
        {
            this.list = list;
        }

        public static GetMediaFromExecutionResponse Deserialize(MessageDeserializer deserializer) => new GetMediaFromExecutionResponse(deserializer);

        private GetMediaFromExecutionResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.list);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.list);
        }

        public override string ToString()
        {
            return "GetMediaFromExecutionResponse: " +
            "\nlist: " + list.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
