//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class GetMissionSwitchResponse : Message
    {
        public const string k_RosMessageName = "sonia_common/GetMissionSwitch";
        public override string RosMessageName => k_RosMessageName;

        public byte state;

        public GetMissionSwitchResponse()
        {
            this.state = 0;
        }

        public GetMissionSwitchResponse(byte state)
        {
            this.state = state;
        }

        public static GetMissionSwitchResponse Deserialize(MessageDeserializer deserializer) => new GetMissionSwitchResponse(deserializer);

        private GetMissionSwitchResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "GetMissionSwitchResponse: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
