//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class GetOverrideMissionSwitchResponse : Message
    {
        public const string k_RosMessageName = "sonia_common/GetOverrideMissionSwitch";
        public override string RosMessageName => k_RosMessageName;

        public byte state;

        public GetOverrideMissionSwitchResponse()
        {
            this.state = 0;
        }

        public GetOverrideMissionSwitchResponse(byte state)
        {
            this.state = state;
        }

        public static GetOverrideMissionSwitchResponse Deserialize(MessageDeserializer deserializer) => new GetOverrideMissionSwitchResponse(deserializer);

        private GetOverrideMissionSwitchResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "GetOverrideMissionSwitchResponse: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
