//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class GetPositionTargetResponse : Message
    {
        public const string k_RosMessageName = "sonia_common/GetPositionTarget";
        public override string RosMessageName => k_RosMessageName;

        public double X;
        public double Y;
        public double Z;
        public double ROLL;
        public double PITCH;
        public double YAW;

        public GetPositionTargetResponse()
        {
            this.X = 0.0;
            this.Y = 0.0;
            this.Z = 0.0;
            this.ROLL = 0.0;
            this.PITCH = 0.0;
            this.YAW = 0.0;
        }

        public GetPositionTargetResponse(double X, double Y, double Z, double ROLL, double PITCH, double YAW)
        {
            this.X = X;
            this.Y = Y;
            this.Z = Z;
            this.ROLL = ROLL;
            this.PITCH = PITCH;
            this.YAW = YAW;
        }

        public static GetPositionTargetResponse Deserialize(MessageDeserializer deserializer) => new GetPositionTargetResponse(deserializer);

        private GetPositionTargetResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.X);
            deserializer.Read(out this.Y);
            deserializer.Read(out this.Z);
            deserializer.Read(out this.ROLL);
            deserializer.Read(out this.PITCH);
            deserializer.Read(out this.YAW);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.X);
            serializer.Write(this.Y);
            serializer.Write(this.Z);
            serializer.Write(this.ROLL);
            serializer.Write(this.PITCH);
            serializer.Write(this.YAW);
        }

        public override string ToString()
        {
            return "GetPositionTargetResponse: " +
            "\nX: " + X.ToString() +
            "\nY: " + Y.ToString() +
            "\nZ: " + Z.ToString() +
            "\nROLL: " + ROLL.ToString() +
            "\nPITCH: " + PITCH.ToString() +
            "\nYAW: " + YAW.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
