//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class KalmannInfoResponse : Message
    {
        public const string k_RosMessageName = "sonia_common/KalmannInfo";
        public override string RosMessageName => k_RosMessageName;

        public double yawUncertainty;
        public double pitchUncertainty;
        public double rollUncertainty;
        public double gyroBiasUncertainty;
        public double magUncertainty;
        public double accelUncertainty;
        public ushort filterStatus;

        public KalmannInfoResponse()
        {
            this.yawUncertainty = 0.0;
            this.pitchUncertainty = 0.0;
            this.rollUncertainty = 0.0;
            this.gyroBiasUncertainty = 0.0;
            this.magUncertainty = 0.0;
            this.accelUncertainty = 0.0;
            this.filterStatus = 0;
        }

        public KalmannInfoResponse(double yawUncertainty, double pitchUncertainty, double rollUncertainty, double gyroBiasUncertainty, double magUncertainty, double accelUncertainty, ushort filterStatus)
        {
            this.yawUncertainty = yawUncertainty;
            this.pitchUncertainty = pitchUncertainty;
            this.rollUncertainty = rollUncertainty;
            this.gyroBiasUncertainty = gyroBiasUncertainty;
            this.magUncertainty = magUncertainty;
            this.accelUncertainty = accelUncertainty;
            this.filterStatus = filterStatus;
        }

        public static KalmannInfoResponse Deserialize(MessageDeserializer deserializer) => new KalmannInfoResponse(deserializer);

        private KalmannInfoResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.yawUncertainty);
            deserializer.Read(out this.pitchUncertainty);
            deserializer.Read(out this.rollUncertainty);
            deserializer.Read(out this.gyroBiasUncertainty);
            deserializer.Read(out this.magUncertainty);
            deserializer.Read(out this.accelUncertainty);
            deserializer.Read(out this.filterStatus);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.yawUncertainty);
            serializer.Write(this.pitchUncertainty);
            serializer.Write(this.rollUncertainty);
            serializer.Write(this.gyroBiasUncertainty);
            serializer.Write(this.magUncertainty);
            serializer.Write(this.accelUncertainty);
            serializer.Write(this.filterStatus);
        }

        public override string ToString()
        {
            return "KalmannInfoResponse: " +
            "\nyawUncertainty: " + yawUncertainty.ToString() +
            "\npitchUncertainty: " + pitchUncertainty.ToString() +
            "\nrollUncertainty: " + rollUncertainty.ToString() +
            "\ngyroBiasUncertainty: " + gyroBiasUncertainty.ToString() +
            "\nmagUncertainty: " + magUncertainty.ToString() +
            "\naccelUncertainty: " + accelUncertainty.ToString() +
            "\nfilterStatus: " + filterStatus.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
