//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class ManageFilterchainRequest : Message
    {
        public const string k_RosMessageName = "sonia_common/ManageFilterchain";
        public override string RosMessageName => k_RosMessageName;

        //  Service to add/remove filterchain
        //  Delete will fail if exec running on it.
        public const byte ADD = 1;
        public const byte DELETE = 2;
        public string filterchain;
        public byte cmd;

        public ManageFilterchainRequest()
        {
            this.filterchain = "";
            this.cmd = 0;
        }

        public ManageFilterchainRequest(string filterchain, byte cmd)
        {
            this.filterchain = filterchain;
            this.cmd = cmd;
        }

        public static ManageFilterchainRequest Deserialize(MessageDeserializer deserializer) => new ManageFilterchainRequest(deserializer);

        private ManageFilterchainRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.filterchain);
            deserializer.Read(out this.cmd);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.filterchain);
            serializer.Write(this.cmd);
        }

        public override string ToString()
        {
            return "ManageFilterchainRequest: " +
            "\nfilterchain: " + filterchain.ToString() +
            "\ncmd: " + cmd.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
