//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class ManageFilterchainFilterResponse : Message
    {
        public const string k_RosMessageName = "sonia_common/ManageFilterchainFilter";
        public override string RosMessageName => k_RosMessageName;

        public const byte SUCCESS = 1;
        public const byte FAIL = 0;
        //  boolean, 1 success, 0 fail.
        public byte success;

        public ManageFilterchainFilterResponse()
        {
            this.success = 0;
        }

        public ManageFilterchainFilterResponse(byte success)
        {
            this.success = success;
        }

        public static ManageFilterchainFilterResponse Deserialize(MessageDeserializer deserializer) => new ManageFilterchainFilterResponse(deserializer);

        private ManageFilterchainFilterResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "ManageFilterchainFilterResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
