//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class ManageFilterchainFilterRequest : Message
    {
        public const string k_RosMessageName = "sonia_common/ManageFilterchainFilter";
        public override string RosMessageName => k_RosMessageName;

        //  Service to add/remove filter from a filterchain
        //  Delete will fail if exec running on it.
        public const byte ADD = 1;
        public const byte DELETE = 2;
        public string exec_name;
        //  If exec_name is null, use filterchain name
        public string filterchain;
        public string filter;
        public byte cmd;

        public ManageFilterchainFilterRequest()
        {
            this.exec_name = "";
            this.filterchain = "";
            this.filter = "";
            this.cmd = 0;
        }

        public ManageFilterchainFilterRequest(string exec_name, string filterchain, string filter, byte cmd)
        {
            this.exec_name = exec_name;
            this.filterchain = filterchain;
            this.filter = filter;
            this.cmd = cmd;
        }

        public static ManageFilterchainFilterRequest Deserialize(MessageDeserializer deserializer) => new ManageFilterchainFilterRequest(deserializer);

        private ManageFilterchainFilterRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.exec_name);
            deserializer.Read(out this.filterchain);
            deserializer.Read(out this.filter);
            deserializer.Read(out this.cmd);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.exec_name);
            serializer.Write(this.filterchain);
            serializer.Write(this.filter);
            serializer.Write(this.cmd);
        }

        public override string ToString()
        {
            return "ManageFilterchainFilterRequest: " +
            "\nexec_name: " + exec_name.ToString() +
            "\nfilterchain: " + filterchain.ToString() +
            "\nfilter: " + filter.ToString() +
            "\ncmd: " + cmd.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
