//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class ModemSendCmdResponse : Message
    {
        public const string k_RosMessageName = "sonia_common/ModemSendCmd";
        public override string RosMessageName => k_RosMessageName;

        public byte role;
        public byte channel;
        public byte link;
        public byte packet_count;
        public byte packet_count_loss;
        public float bit_error_rate;
        public byte queue_length;

        public ModemSendCmdResponse()
        {
            this.role = 0;
            this.channel = 0;
            this.link = 0;
            this.packet_count = 0;
            this.packet_count_loss = 0;
            this.bit_error_rate = 0.0f;
            this.queue_length = 0;
        }

        public ModemSendCmdResponse(byte role, byte channel, byte link, byte packet_count, byte packet_count_loss, float bit_error_rate, byte queue_length)
        {
            this.role = role;
            this.channel = channel;
            this.link = link;
            this.packet_count = packet_count;
            this.packet_count_loss = packet_count_loss;
            this.bit_error_rate = bit_error_rate;
            this.queue_length = queue_length;
        }

        public static ModemSendCmdResponse Deserialize(MessageDeserializer deserializer) => new ModemSendCmdResponse(deserializer);

        private ModemSendCmdResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.role);
            deserializer.Read(out this.channel);
            deserializer.Read(out this.link);
            deserializer.Read(out this.packet_count);
            deserializer.Read(out this.packet_count_loss);
            deserializer.Read(out this.bit_error_rate);
            deserializer.Read(out this.queue_length);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.role);
            serializer.Write(this.channel);
            serializer.Write(this.link);
            serializer.Write(this.packet_count);
            serializer.Write(this.packet_count_loss);
            serializer.Write(this.bit_error_rate);
            serializer.Write(this.queue_length);
        }

        public override string ToString()
        {
            return "ModemSendCmdResponse: " +
            "\nrole: " + role.ToString() +
            "\nchannel: " + channel.ToString() +
            "\nlink: " + link.ToString() +
            "\npacket_count: " + packet_count.ToString() +
            "\npacket_count_loss: " + packet_count_loss.ToString() +
            "\nbit_error_rate: " + bit_error_rate.ToString() +
            "\nqueue_length: " + queue_length.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
