//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class ModemSendCmdRequest : Message
    {
        public const string k_RosMessageName = "sonia_common/ModemSendCmd";
        public override string RosMessageName => k_RosMessageName;

        public byte cmd;
        public byte role;
        public byte channel;

        public ModemSendCmdRequest()
        {
            this.cmd = 0;
            this.role = 0;
            this.channel = 0;
        }

        public ModemSendCmdRequest(byte cmd, byte role, byte channel)
        {
            this.cmd = cmd;
            this.role = role;
            this.channel = channel;
        }

        public static ModemSendCmdRequest Deserialize(MessageDeserializer deserializer) => new ModemSendCmdRequest(deserializer);

        private ModemSendCmdRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cmd);
            deserializer.Read(out this.role);
            deserializer.Read(out this.channel);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cmd);
            serializer.Write(this.role);
            serializer.Write(this.channel);
        }

        public override string ToString()
        {
            return "ModemSendCmdRequest: " +
            "\ncmd: " + cmd.ToString() +
            "\nrole: " + role.ToString() +
            "\nchannel: " + channel.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
