//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class ObjectiveLocationResponse : Message
    {
        public const string k_RosMessageName = "sonia_common/ObjectiveLocation";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg position;

        public ObjectiveLocationResponse()
        {
            this.position = new Geometry.PointMsg();
        }

        public ObjectiveLocationResponse(Geometry.PointMsg position)
        {
            this.position = position;
        }

        public static ObjectiveLocationResponse Deserialize(MessageDeserializer deserializer) => new ObjectiveLocationResponse(deserializer);

        private ObjectiveLocationResponse(MessageDeserializer deserializer)
        {
            this.position = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
        }

        public override string ToString()
        {
            return "ObjectiveLocationResponse: " +
            "\nposition: " + position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
