//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class OverrideMissionSwitchRequest : Message
    {
        public const string k_RosMessageName = "sonia_common/OverrideMissionSwitch";
        public override string RosMessageName => k_RosMessageName;

        public byte state;

        public OverrideMissionSwitchRequest()
        {
            this.state = 0;
        }

        public OverrideMissionSwitchRequest(byte state)
        {
            this.state = state;
        }

        public static OverrideMissionSwitchRequest Deserialize(MessageDeserializer deserializer) => new OverrideMissionSwitchRequest(deserializer);

        private OverrideMissionSwitchRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "OverrideMissionSwitchRequest: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
