//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class RepublishRequest : Message
    {
        public const string k_RosMessageName = "sonia_common/Republish";
        public override string RosMessageName => k_RosMessageName;

        // Command to start/stop DetectionTask
        public const byte START = 1;
        public const byte STOP = 2;
        public string topic_name;
        // the defined up there.
        public byte cmd;

        public RepublishRequest()
        {
            this.topic_name = "";
            this.cmd = 0;
        }

        public RepublishRequest(string topic_name, byte cmd)
        {
            this.topic_name = topic_name;
            this.cmd = cmd;
        }

        public static RepublishRequest Deserialize(MessageDeserializer deserializer) => new RepublishRequest(deserializer);

        private RepublishRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.topic_name);
            deserializer.Read(out this.cmd);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.topic_name);
            serializer.Write(this.cmd);
        }

        public override string ToString()
        {
            return "RepublishRequest: " +
            "\ntopic_name: " + topic_name.ToString() +
            "\ncmd: " + cmd.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
