//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class SetAUVServiceRequest : Message
    {
        public const string k_RosMessageName = "sonia_common/SetAUVService";
        public override string RosMessageName => k_RosMessageName;

        public string object_name;

        public SetAUVServiceRequest()
        {
            this.object_name = "";
        }

        public SetAUVServiceRequest(string object_name)
        {
            this.object_name = object_name;
        }

        public static SetAUVServiceRequest Deserialize(MessageDeserializer deserializer) => new SetAUVServiceRequest(deserializer);

        private SetAUVServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.object_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.object_name);
        }

        public override string ToString()
        {
            return "SetAUVServiceRequest: " +
            "\nobject_name: " + object_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
