//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SoniaCommon
{
    [Serializable]
    public class SetSimulationAUVResponse : Message
    {
        public const string k_RosMessageName = "sonia_common/SetSimulationAUV";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public SetSimulationAUVResponse()
        {
            this.success = false;
        }

        public SetSimulationAUVResponse(bool success)
        {
            this.success = success;
        }

        public static SetSimulationAUVResponse Deserialize(MessageDeserializer deserializer) => new SetSimulationAUVResponse(deserializer);

        private SetSimulationAUVResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "SetSimulationAUVResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
