//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class SetAUVServiceResponse : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/SetAUVService";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public SetAUVServiceResponse()
        {
            this.success = false;
        }

        public SetAUVServiceResponse(bool success)
        {
            this.success = success;
        }

        public static SetAUVServiceResponse Deserialize(MessageDeserializer deserializer) => new SetAUVServiceResponse(deserializer);

        private SetAUVServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "SetAUVServiceResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
