//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.AuvPackage
{
    public class CameraDatacopy : Message
    {
        public const string RosMessageName = "auv_package/CameraDatacopy";

        public Sensor.Image Message;

        public CameraDatacopy()
        {
            this.Message = new Sensor.Image();
        }

        public CameraDatacopy(Sensor.Image Message)
        {
            this.Message = Message;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(Message.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.Message.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "CameraDatacopy: " +
            "\nMessage: " + Message.ToString();
        }
    }
}
